package com.univaq.platformsfinder.model;

import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;

import java.util.List;


/**
 * The interface Platforms dao.
 */
@Dao
public interface PlatformsDao
{
    /**
     * Gets platforms List generated by the JSON file and inserts it in the DB
     *
     * @param platformsList the platforms list
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    void insertPlatforms(List<PlatformTable> platformsList);

    /**
     * Gets all platforms from DB
     *
     * @return All platfroms list
     */
    @Query("SELECT * FROM platformtable")
    List<PlatformTable> getPlatforms();

    /**
     * Gets platform by coordinates
     *
     * @param mylat latitude
     * @param mylon longitude
     * @return the specific platform
     */
    @Query("SELECT * FROM platformtable WHERE latitudine LIKE :mylat AND longitudine LIKE :mylon")
    PlatformTable getPlatform(double mylat, double mylon);

    /**
     * Gets platform by id.
     *
     * @param id
     * @return the specific platform
     */
    @Query("SELECT * FROM platformtable WHERE id LIKE :id")
    PlatformTable getPlatformByID(int id);
}
